export const Tags = [
  // Clubs
  "Real Madrid",
  "Barcelona",
  "Manchester United",
  "Manchester City",
  "Liverpool",
  "Chelsea",
  "Arsenal",
  "Bayern Munich",
  "PSG",
  "Juventus",
  "AC Milan",
  "Inter Milan",
  "Atletico Madrid",
  "Borussia Dortmund",
  "Tottenham",
  "Napoli",
  "AS Roma",
  "Sevilla",
  "Newcastle United",
  "Ajax",
  "RB Leipzig",
  "Marseille",
  "Porto",
  "Benfica",
  "Sporting CP",
  "Lazio",
  "Feyenoord",
  "Galatasaray",
  "Besiktas",
  "Fenerbahce",
  "Celtic",
  "Rangers",
  "Shakhtar Donetsk",
  "Dynamo Kyiv",
  "Club Brugge",
  "Flamengo",
  "Boca Juniors",
  "River Plate",
  "Santos",
  "Gremio",
  "Palmeiras",
  "Corinthians",
  "Al Nassr",
  "Al Hilal",
  "Al Ahly",
  "Zamalek",
  "Tigres",
  "Monterrey",
  "Atlanta United",

  // Tournaments
  "UEFA Champions League",
  "UEFA Europa League",
  "Premier League",
  "La Liga",
  "Bundesliga",
  "Serie A",
  "Ligue 1",
  "Eredivisie",
  "Copa del Rey",
  "FA Cup",
  "Carabao Cup",
  "Copa Italia",
  "DFB Pokal",
  "Community Shield",
  "Supercopa de España",
  "Copa Libertadores",
  "FIFA Club World Cup",
  "AFC Champions League",
  "CONCACAF Champions Cup",
  "Europa Conference League",
  "Euro 2024",
  "Copa America",
  "AFCON",
  "Asian Cup",
  "Gold Cup",
  "World Cup",
  "Nations League",
  "U20 World Cup",
  "U17 World Cup",
  "Brazilian Serie A",
  "Argentine Primera Division",
  "MLS Cup",

  // Countries
  "Argentina",
  "Brazil",
  "Spain",
  "France",
  "Germany",
  "England",
  "Portugal",
  "Italy",
  "Netherlands",
  "Belgium",
  "Croatia",
  "Uruguay",
  "Mexico",
  "USA",
  "Japan",
  "South Korea",
  "Senegal",
  "Morocco",
  "Nigeria",
  "Colombia",
  "Chile",
  "Ecuador",
  "Australia",
  "Switzerland",
  "Denmark",
  "Poland",
  "Sweden",
  "Serbia",
  "Turkey",
  "Ghana",
  "Egypt",
  "Iran",
  "Paraguay",
  "Peru",
  "Norway",

  // Players
  "Cristiano Ronaldo",
  "Lionel Messi",
  "Kylian Mbappe",
  "Erling Haaland",
  "Kevin De Bruyne",
  "Neymar",
  "Jude Bellingham",
  "Vinicius Jr",
  "Rodrygo",
  "Harry Kane",
  "Robert Lewandowski",
  "Luka Modric",
  "Toni Kroos",
  "Karim Benzema",
  "Mohamed Salah",
  "Bruno Fernandes",
  "Marcus Rashford",
  "Bukayo Saka",
  "Martin Ødegaard",
  "Joshua Kimmich",
  "Pedri",
  "Gavi",
  "Antoine Griezmann",
  "Rafael Leão",
  "Lautaro Martinez",
  "Declan Rice",
  "João Félix",
  "Frenkie de Jong",
  "Phil Foden",
  "Jamal Musiala",
  "Christopher Nkunku",
  "Victor Osimhen",
  "Darwin Nuñez",
  "Federico Valverde",
  "Achraf Hakimi",
  "Trent Alexander-Arnold",
  "Andrew Robertson",
  "Reece James",
  "Jadon Sancho",
  "Gabriel Martinelli",
  "Leandro Trossard",
  "Khvicha Kvaratskhelia",
  "Aleksandar Mitrovic",
  "Heung-min Son",
  "James Maddison",
  "Thiago Alcantara",
  "Casemiro",
  "Eduardo Camavinga",
  "Aurélien Tchouaméni",
  "Lisandro Martinez",
  "Sandro Tonali",
  "Joško Gvardiol",
  "Ruben Dias",
  "Eder Militao",
  "Alisson Becker",
  "Ederson",
  "Gianluigi Donnarumma",
  "Mike Maignan",
  "Yassine Bounou (Bono)",
  "Emiliano Martinez",

  // More Players Added
  "Paulo Dybala",
  "Angel Di Maria",
  "Julian Alvarez",
  "Dusan Vlahovic",
  "Dominik Szoboszlai",
  "Kai Havertz",
  "Mason Mount",
  "Randal Kolo Muani",
  "Matthijs de Ligt",
  "Alphonso Davies",
  "Benjamin Pavard",
  "Jorginho",
  "Nicolo Barella",
  "Sergej Milinković-Savić",
  "Hakan Çalhanoğlu",
  "Cody Gakpo",
  "Marcus Thuram",
  "Jonathan David",
  "Alexander Isak",
  "Florian Wirtz",
  "Enzo Fernandez",
  "Moises Caicedo",
  "Pablo Gavi",
  "João Cancelo",
  "Jules Koundé",
  "Ronald Araújo",
  "Presnel Kimpembe",
  "William Saliba",
  "Kieran Trippier",
  "Lautaro Martínez",
  "Youssoufa Moukoko",
  "Giovanni Reyna",
  "Pedri González",
  "Moussa Diaby",
  "Arda Güler",
  "Mykhailo Mudryk",
  "Riyad Mahrez",
  "Sergio Busquets",
  "Marco Verratti",
  "Dani Carvajal",
  "David Alaba",
  "Nico Williams",
  "Rodri",
  "Manuel Neuer",
  "Thibaut Courtois",
  "Marc-André ter Stegen",
  "Bruno Guimarães",
  "Lucas Paquetá",
  "Sofyan Amrabat",
  "Brahim Díaz",
  "Gabriel Jesus",
  "Tammy Abraham",
  "Wissam Ben Yedder",
  "Pedro Gonçalves",
  "Federico Chiesa",
  "Zlatan Ibrahimović (if still playing)",
  "Gerard Moreno",
  "João Moutinho",
  "Pepe",
  "Raphael Varane",
  "Aymeric Laporte",
  "Stefan de Vrij",
  "Kalvin Phillips",
  "Mikel Merino",
  "Thiago Silva",
  "Jordan Pickford",
  "Hugo Lloris",
  "Gianluca Scamacca",
  "Olivier Giroud",

  // Coaches (Removed less popular ones)
  "Carlo Ancelotti",
  "Pep Guardiola",
  "Jurgen Klopp",
  "Jose Mourinho",
  "Zinedine Zidane",
  "Xavi",
  "Mikel Arteta",
  "Thomas Tuchel",
  "Diego Simeone",
  "Luis Enrique",
  "Didier Deschamps",
  "Hansi Flick",
  "Erik ten Hag",
  "Unai Emery",
  "Julian Nagelsmann",

  // Other Football Terms
  "VAR",
  "Offside",
  "Penalty",
  "Free Kick",
  "Corner Kick",
  "Yellow Card",
  "Red Card",
  "Hat-trick",
  "Goalkeeper",
  "Defender",
  "Midfielder",
  "Striker",
  "Assist",
  "Clean Sheet",
  "Formation",
  "Tactics",
  "Counter Attack",
  "Pressing",
  "Possession",
  "Injury Time",
  "Stoppage Time",
  "Extra Time",
  "Penalty Shootout",
  "Transfer Window",
  "Loan Move",
  "Buyout Clause",
  "Salary Cap",
  "Golden Boot",
  "Ballon d'Or",
  "The Treble",
  "El Clasico",
  "Derby",
  "Top Scorer",
  "Best XI",
];
